source 'https://rubygems.org'

gem 'rails', '3.2.8'
gem 'rspec-rails', '2.8.1'
gem 'braintree', '>= 2.16.0'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
